### ISSUE TITLE
Windows 10 obsidian 1.1.9 buttons disappear

### ISSUE THREAD

**Issue by youonlytrackonce** [PipeItToDevNull/PLN#15]
Hi,

as stated in the heading, settings, help, open another vault etc buttons dissapper when I enable PLN theme. I cannot change any settings so I cannot quit. When I delete PLN in themes folder, I can change the theme. Could you please fix this issue?

Thanks.

**Comment by PipeItToDevNull** [comment]
This is an intentional default, it accomplishes what is shown in the themes screenshots. 

Access to the various panels can be accomplished via the command palette, CMD-P on Mac or CTRL-P on Windows. 

Using Style Settings the the "Ribbon" can be re-enabled under PLN>Removals

**Comment by youonlytrackonce** [comment]
Hi,

thank you very much for your quick response. I have been using your theme on my iphone (ios 16.3.1), my home laptop (windows 10) and university desktop (ubuntu 20.04). I have experienced this default behavior only on windows. My problem is solved. Thanks.
