### ISSUE TITLE
How can I open the sidebar of my obsidian after using your theme created by you?

### ISSUE THREAD

**Issue by MinJohnson** [PipeItToDevNull/PLN#17]

**Comment by PipeItToDevNull** [comment]
The community plugin "Style Settings" would be able to bring that back, it contains all the options for this and many other themes.

Install Style Settings then open its settings and go to "PLN > Removals > Remove ribbon" and toggle that Off

**Comment by MinJohnson** [comment]
Ok,I have found it, Thank you! The theme of you is very wonderful!







                       
原始邮件
                       
                     

发件人："PipeItToDevNull"< ***@***.*** &gt;;

发件时间：2023/4/10 20:01

收件人："PipeItToDevNull/PLN"< ***@***.*** &gt;;

抄送人："MinJohnson"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [PipeItToDevNull/PLN] How can I open the sidebar of my obsidianafter using your theme created by you? (Issue #17)




 
The community plugin "Style Settings" would be able to bring that back, it contains all the options for this and many other themes.
 
Install Style Settings then open its settings and go to "PLN &gt; Removals &gt; Remove ribbon" and toggle that Off
 
&mdash;

**Comment by PipeItToDevNull** [comment]
Glad you like it and glad you got that sorted out.
