### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bbecausereasonss** [PipeItToDevNull/PLN#20]
Hey there love the theme overall. Few questions.

1. Can we have an option to change the base theme color? That blueish-grey?
2. It seems not possible to disable a highlight of the current line, even when its off.

**Comment by PipeItToDevNull** [comment]
When in both Source and Live Preview view I am able to highlight or not highlight the current line with the Style Setting "General modifications > Highlight active line"

Can you validate this issue occurs when you have no snippets enabled?

**Comment by PipeItToDevNull** [comment]
Colors are not in style settings with the 1.9.0 update
