### ISSUE TITLE
Way to hide file attachments but not Canvas?

### ISSUE THREAD

**Issue by wildefae** [PipeItToDevNull/PLN#24]
Hi, I love PLN and for the most part I agree with (or can just shut off in style settings) the removals, but it took me forever to realize that the reason I couldn't see my Canvases was that it gets shut off by the "hide attachments" setting. 

I actually really like "hide attachments" because for the most part, it just hides my insane number of copy/pasted screencaps. But Canvases, I do need because they're a separate page and embedding them is a really annoying way to access them since it basically shows you a useless thumbnail you have to click on to get to the real file instead of a full size canvas. 

Is there a way to split off Canvases from the other .md files to enable?

**Comment by PipeItToDevNull** [comment]
I don't use canvases so I never would have seen that issue, but lemme take a peak at how this can best be addressed.

**Comment by wildefae** [comment]
Thanks so much for the fast response!

**Comment by PipeItToDevNull** [comment]
If you update the theme you should see a new Style Settings category called "Attachment options" where you can hide all attachments the unhide specific ones

**Comment by wildefae** [comment]
You're awesome, thank you!!
