### ISSUE TITLE
Control buttons in Advanced Slides are missing

### ISSUE THREAD

**Issue by Sk1nk** [PipeItToDevNull/PLN#28]
Since I am new to Obsidian and want to combine my lectures with the place I take my notes (because it is much easier to work in tabs than on different programs that I have to arrange myself) I played around with the "Slides" plugin, but since this didn't provide everything I needed, I quickly changed to "Advanced slides".

One of the core features is the Live preview tab, which works fine. But in the standard UI there are 4 buttons in the top left, one of them being to start the actual presentation ... which go missing in your theme. Could You find a way to bring them back?

![Bildschirmfoto 2024-08-04 um 14 40 11](https://github.com/user-attachments/assets/64699c63-7d78-42b0-a766-86b3c852178e)
Buttons top right are shown in standard UI

![Bildschirmfoto 2024-08-04 um 14 40 29](https://github.com/user-attachments/assets/6c3f0cf8-6292-4a4a-84f5-7f4ef8040bb8)
Buttons missing in your theme

**Comment by PipeItToDevNull** [comment]
I do not use this plugin but I can install it if necessary, can you add the Style Settings plugin to validate that any of my settings won't already resolve this?

**Comment by Sk1nk** [comment]
It did! The "Remove view actions" is what removed the buttons in the top right. Toggled it! Thanks!
